# House Rent Prediction

## Objective :

### import required packages

In [121]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Read the dataset

In [122]:
dataset = pd.read_csv("House_rent_unclean.csv")

### Data Pre-Processing

In [123]:
# Delete the unnamed column which is unnecessary is there in database
dataset.drop("Unnamed: 0",inplace=True,axis=1)

### Exploratory Data Analysis

In [124]:
# checking the data in dataset
dataset.head()

seller_type  bedroom layout_type      property_type     locality    price  \
0       OWNER      2.0         BHK          Apartment     Bodakdev  20000.0   
1       OWNER      1.0          RK   Studio Apartment      CG Road   7350.0   
2       OWNER      3.0         BHK          Apartment      Jodhpur  22000.0   
3       OWNER      2.0         BHK  Independent House       Sanand  13000.0   
4       OWNER      2.0         BHK  Independent House  Navrangpura  18000.0   

     area    furnish_type  bathroom       city  
0  1450.0       Furnished       2.0  Ahmedabad  
1   210.0  Semi-Furnished       1.0  Ahmedabad  
2  1900.0     Unfurnished       3.0  Ahmedabad  
3  1285.0  Semi-Furnished       2.0  Ahmedabad  
4  1600.0       Furnished       2.0  Ahmedabad

In [125]:
# Checking the count of the types in every dimension
dataset.count()

seller_type      192688
bedroom          192809
layout_type      192997
property_type    192500
locality         193011
price            192264
area             192012
furnish_type     192933
bathroom         192827
city             192665
dtype: int64

#### Cheking for unique values

In [126]:
# cheking seller type categories
pd.unique(dataset["seller_type"])

array(['OWNER', 'AGENT', nan, 'BUILDER'], dtype=object)

In [127]:
# Checking for bedroom categories
pd.unique(dataset["bedroom"])

array([ 2.,  1.,  3.,  4.,  5., nan,  6., 10.,  7.,  8., 15.,  9., 12.,
       14., 11.])

In [128]:
# checking for layout_type
pd.unique(dataset["layout_type"])

array(['BHK', 'RK', nan], dtype=object)

In [129]:
# cheking for property type
pd.unique(dataset["property_type"])

array(['Apartment', 'Studio Apartment', 'Independent House',
       'Independent Floor', 'Villa', nan, 'Penthouse'], dtype=object)

In [130]:
# checking for locality type
pd.unique(dataset["locality"])

array(['Bodakdev', 'CG Road', 'Jodhpur', ..., 'Renuka Nagar',
       'Gananjay Society', 'Aundh Gaon'], dtype=object)

In [131]:
# checking for the furnish type
pd.unique(dataset["furnish_type"])

array(['Furnished', 'Semi-Furnished', 'Unfurnished', nan], dtype=object)

In [132]:
# checking for the bathroom
pd.unique(dataset["bathroom"])

array([ 2.,  1.,  3.,  4.,  5., nan,  6., 12.,  7.,  8., 15.,  9., 18.,
       19., 10., 16., 14.])

In [133]:
# checking for the city
pd.unique(dataset["city"])

array(['Ahmedabad', nan, 'Bangalore', 'Chennai', 'Delhi', 'Hyderabad',
       'Kolkata', 'Mumbai', 'Pune'], dtype=object)

#### Checking for Null Values

In [134]:
dataset.isna().sum()

seller_type      323
bedroom          202
layout_type       14
property_type    511
locality           0
price            747
area             999
furnish_type      78
bathroom         184
city             346
dtype: int64

#### Handling NaN Values

In [135]:
# Calculating with mode values
dataset.mode()

seller_type  bedroom layout_type property_type    locality    price    area  \
0       AGENT      2.0         BHK     Apartment  Thane West  15000.0  1200.0   

     furnish_type  bathroom    city  
0  Semi-Furnished       2.0  Mumbai

In [136]:
# Replace all the values with mode values of every dimension
values = {"seller_type": "AGENT", "bedroom": 2.0, "layout_type": "BHK", "property_type":"Apartment","locality":"Thane West","price":1200.0,"area":1200.0,"furnish_type":"Semi-Furnished","bathroom":2.0,"city":"Mumbai"}
dataset.fillna(inplace=True,value=values)
dataset.isna().sum()

seller_type      0
bedroom          0
layout_type      0
property_type    0
locality         0
price            0
area             0
furnish_type     0
bathroom         0
city             0
dtype: int64

### Data Set Saving

In [137]:
dataset.to_csv("No null Values")

#### Data Balance Checking

In [138]:
# data balance check for seller type
dataset["seller_type"].value_counts()

seller_type
AGENT      153014
OWNER       38651
BUILDER      1346
Name: count, dtype: int64

In [139]:
# data balance check for bedroom
dataset["bedroom"].value_counts()

bedroom
2.0     77221
1.0     58166
3.0     44293
4.0     11562
5.0      1389
6.0       147
10.0       76
8.0        50
7.0        48
15.0       23
9.0        23
12.0        6
14.0        4
11.0        3
Name: count, dtype: int64

In [140]:
# data balance check for layout type
dataset["layout_type"].value_counts()

layout_type
BHK    183749
RK       9262
Name: count, dtype: int64

In [141]:
# data balace check for property type
dataset["property_type"].value_counts()

property_type
Apartment            140481
Independent Floor     27221
Independent House     12805
Studio Apartment       9237
Villa                  3111
Penthouse               156
Name: count, dtype: int64

In [142]:
# data balance check for locality
dataset["locality"].value_counts()

locality
Thane West                 4478
Chembur                    3549
Andheri East               3415
Bopal                      2933
Kharghar                   2614
                           ... 
Kuthambakkam                  1
Agaramthen                    1
Daighar Gaon                  1
Mettukuppam Kanchipuram       1
Aundh Gaon                    1
Name: count, Length: 4146, dtype: int64

In [143]:
# data balance check for area
dataset["area"].value_counts()

area
1200.0    9409
600.0     7378
1000.0    7231
650.0     5773
900.0     5442
          ... 
9004.0       1
6825.0       1
2523.0       1
2312.0       1
258.0        1
Name: count, Length: 2761, dtype: int64

In [144]:
# data balance check for furnish type
dataset["furnish_type"].value_counts()

furnish_type
Semi-Furnished    95769
Unfurnished       58668
Furnished         38574
Name: count, dtype: int64

In [145]:
# data balance check for bathroom
dataset["bathroom"].value_counts()

bathroom
2.0     90155
1.0     54218
3.0     35418
4.0     10664
5.0      1926
6.0       381
7.0        80
9.0        55
8.0        52
10.0       34
15.0        8
16.0        6
14.0        6
12.0        5
19.0        2
18.0        1
Name: count, dtype: int64

In [146]:
# data balancing check for city
dataset["city"].value_counts()

city
Mumbai       67654
Delhi        32542
Bangalore    23028
Pune         22558
Ahmedabad    18413
Hyderabad    10527
Kolkata       9645
Chennai       8644
Name: count, dtype: int64

#### Data Types and Dimension Checking

In [147]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193011 entries, 0 to 193010
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   seller_type    193011 non-null  object 
 1   bedroom        193011 non-null  float64
 2   layout_type    193011 non-null  object 
 3   property_type  193011 non-null  object 
 4   locality       193011 non-null  object 
 5   price          193011 non-null  float64
 6   area           193011 non-null  float64
 7   furnish_type   193011 non-null  object 
 8   bathroom       193011 non-null  float64
 9   city           193011 non-null  object 
dtypes: float64(4), object(6)
memory usage: 14.7+ MB


## Encoding

In [148]:
# Lable Encoding for all categorical columns
# importing LabelEncoder
from sklearn.preprocessing import LabelEncoder

#making encoder object
encoder = LabelEncoder()

#Start Encoding
dataset["seller_type"] = encoder.fit_transform(dataset["seller_type"])
# print(encoder.get_params())
print(encoder.classes_)
dataset["bedroom"]     = encoder.fit_transform(dataset["bedroom"])
print(encoder.classes_)
dataset["layout_type"] = encoder.fit_transform(dataset["layout_type"])
print(encoder.classes_)
dataset["property_type"] = encoder.fit_transform(dataset["property_type"])
print(encoder.classes_)
dataset["locality"] = encoder.fit_transform(dataset["locality"])
print(encoder.classes_)
dataset["furnish_type"] = encoder.fit_transform(dataset["furnish_type"])
print(encoder.classes_)
dataset["bathroom"] = encoder.fit_transform(dataset["bathroom"])
print(encoder.classes_)
dataset["city"] = encoder.fit_transform(dataset["city"])
print(encoder.classes_)


{}
['AGENT' 'BUILDER' 'OWNER']
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 14. 15.]
['BHK' 'RK']
['Apartment' 'Independent Floor' 'Independent House' 'Penthouse'
 'Studio Apartment' 'Villa']
['1 Sector Number 3 Road' '10 Sector Number 3 Road'
 '10 Sector Number 6 Road' ... 'wakad' 'worli sea Fase' 'yogi nagar']
['Furnished' 'Semi-Furnished' 'Unfurnished']
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 12. 14. 15. 16. 18. 19.]
['Ahmedabad' 'Bangalore' 'Chennai' 'Delhi' 'Hyderabad' 'Kolkata' 'Mumbai'
 'Pune']


In [31]:
dataset["seller_type"]

0         2
1         2
2         2
3         2
4         2
         ..
193006    2
193007    2
193008    2
193009    0
193010    0
Name: seller_type, Length: 193011, dtype: int64

In [31]:
# all the values in int & float
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193011 entries, 0 to 193010
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   seller_type    193011 non-null  int64  
 1   bedroom        193011 non-null  int64  
 2   layout_type    193011 non-null  int64  
 3   property_type  193011 non-null  int64  
 4   locality       193011 non-null  int64  
 5   price          193011 non-null  float64
 6   area           193011 non-null  float64
 7   furnish_type   193011 non-null  int64  
 8   bathroom       193011 non-null  int64  
 9   city           193011 non-null  int64  
dtypes: float64(2), int64(8)
memory usage: 14.7 MB


## Save Data 

In [32]:
dataset.to_csv("Hello")

### Data Processing

In [33]:
# price is dependant columns

X = dataset.drop("price",axis = 1)
Y = dataset["price"]


In [34]:
# Split the data into Train and Test
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,train_size=0.7,random_state=12345)

## Model Building

In [35]:
def linear_regression_model():
    from sklearn.linear_model import LinearRegression
    model = LinearRegression()
    model.fit(X_train,Y_train)
    return model

In [36]:
def decision_tree_model():
    from sklearn.tree import DecisionTreeRegressor
    model = DecisionTreeRegressor()
    model.fit(X_train,Y_train)
    return model

In [37]:
def random_forest_model():
    from sklearn.ensemble import RandomForestRegressor
    model = RandomForestRegressor()
    model.fit(X_train,Y_train)
    return model

In [38]:
def catBoost_model():
    from catboost import CatBoostRegressor
    model = CatBoostRegressor()
    model.fit(X_train,Y_train)
    return model

In [39]:
def xgBoost_model():
    from xgboost import XGBRegressor
    model = XGBRegressor()
    model.fit(X_train,Y_train)
    return model

In [40]:
# reference variable
linear_regression = linear_regression_model()
decision_tree = decision_tree_model()
catboost = catBoost_model()
xgboost = xgBoost_model()

Learning rate set to 0.088885
0:	learn: 86224.2776891	total: 63.9ms	remaining: 1m 3s
1:	learn: 81569.8462786	total: 76.5ms	remaining: 38.2s
2:	learn: 77522.3077687	total: 86.2ms	remaining: 28.6s
3:	learn: 73886.6356651	total: 94.1ms	remaining: 23.4s
4:	learn: 70595.1454608	total: 102ms	remaining: 20.3s
5:	learn: 67769.6783843	total: 109ms	remaining: 18.1s
6:	learn: 65257.3447783	total: 116ms	remaining: 16.4s
7:	learn: 62955.0771695	total: 123ms	remaining: 15.3s
8:	learn: 60921.7957986	total: 131ms	remaining: 14.4s
9:	learn: 59181.9634504	total: 138ms	remaining: 13.6s
10:	learn: 57557.5596193	total: 145ms	remaining: 13s
11:	learn: 56214.8701047	total: 152ms	remaining: 12.5s
12:	learn: 54964.4051736	total: 159ms	remaining: 12s
13:	learn: 53923.4455456	total: 166ms	remaining: 11.7s
14:	learn: 52984.8477661	total: 173ms	remaining: 11.3s
15:	learn: 52168.4761931	total: 180ms	remaining: 11.1s
16:	learn: 51361.4199054	total: 188ms	remaining: 10.9s
17:	learn: 50678.1059099	total: 198ms	remaini

/home/anant/.local/lib/python3.10/site-packages/xgboost/data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
/home/anant/.local/lib/python3.10/site-packages/xgboost/data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
/home/anant/.local/lib/python3.10/site-packages/xgboost/data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
/home/anant/.local/lib/python3.10/site-packages/xgboost/data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return is_int or is_bool or is_float or is_catego

## Model Evaluation

In [41]:
def model_evaluation(model):
    from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
    
    y_true = Y_test
    y_pred = model.predict(X_test)
    print(f"Mean Absolute Error = {mean_absolute_error(y_true,y_pred):.2f}")
    print(f"Mean Squared Error = {mean_squared_error(y_true,y_pred):.2f}")
    print(f"R2 Square = {r2_score(y_true,y_pred)*100:.2f}%")
    

In [46]:
model_evaluation(linear_regression)

Mean Absolute Error = 27258.99
Mean Squared Error = 3370918559.50
R2 Square = 60.78%


In [45]:
model_evaluation(decision_tree)

Mean Absolute Error = 8893.45
Mean Squared Error = 1849724353.99
R2 Square = 78.48%


In [52]:
model_evaluation(catboost)

Mean Absolute Error = 11243.27
Mean Squared Error = 1356098014.59
R2 Square = 84.22%


In [42]:
model_evaluation(xgboost)

Mean Absolute Error = 10904.60
Mean Squared Error = 1253975270.04
R2 Square = 85.41%


/home/anant/.local/lib/python3.10/site-packages/xgboost/data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
/home/anant/.local/lib/python3.10/site-packages/xgboost/data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
/home/anant/.local/lib/python3.10/site-packages/xgboost/data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
/home/anant/.local/lib/python3.10/site-packages/xgboost/data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return is_int or is_bool or is_float or is_catego

## Save the model 

In [45]:
import pickle

with open("xgboost.pkl","wb") as file:
    pickle.dump(xgBoost_model(),file)

/home/anant/.local/lib/python3.10/site-packages/xgboost/data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
/home/anant/.local/lib/python3.10/site-packages/xgboost/data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
/home/anant/.local/lib/python3.10/site-packages/xgboost/data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
/home/anant/.local/lib/python3.10/site-packages/xgboost/data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return is_int or is_bool or is_float or is_catego